title: Joshua Layfield AI Artifacts
email: jlayfield@stthomas.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jolayfield.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jolayfield   
tagline: AI-built artifacts, outputs, and process notes.
author: Joshua Layfield 
# Build settings
theme: minima
plugins:
  - jekyll-feed
